- tasks/install-debian.yml
This removes the warning when running ansible with this role:
[WARNING]: Consider using get_url or uri module rather than running curl
> fix: remove warning from Ansible 2.2

- tasks/install-debian.yml
Hi,
We have noticed that this role updates the `gitlab-ci-multi-runner` binary automatically at each run of this role.
I though it was better to create a new task list or role for updates.
Indeed you don't alway expect the binary to be updated at each run of this role (especially when it's run automatically in a CI/CD fashion).
What do you think about this patch?
> debian: add possibility to fix package version number

- defaults/main.yml
Auto-detect runner concurrency based on total CPU threads (vcpus), instead of only processor cores. This accounts for both multiple cores and multiple processors.
For example, some virtual machines will detect as having multiple discrete processors (1 core each) instead of one processor with multiple cores. And some physical servers have 2 (or more) processor sockets.
See https://stackoverflow.com/questions/39539559/ansible-procesor-count-vs-processor-cores-vs-processor-vcpus
> Fix concurrency auto-detection

- tasks/register-runner.yml
When running the playbook in `--check` mode, `gitlab-runner list` still needs to register a result to prevent an error on the following `when` clause.
> Fix registration check when in Ansible check-mode

- README.md
- defaults/main.yml
- tasks/register-runner.yml
When registering multiple runner on the same host, we may want to enforce a limit different than the global one.
> Add limit option for specific runner

- tasks/register-runner.yml
The `gitlab-runner register` command may include secrets such as S3 secret keys, SSH passwords etc. which should not be logged or output to the console for security reasons.
> Ensure credentials not stored in any log file or console output

- tasks/install-debian.yml
Hi, I noticed that "Install Gitlab repository" task is not idempotent. Here's my fix.
Thanks, bye.
--domenico
> Add creates to fix non-idempotent task Install Gitlab repository

- tasks/install-redhat.yml
Fix
```
TASK [riemers.gitlab-runner : Install GitLab Runner dependencies] ****************************
[DEPRECATION WARNING]: Invoking "yum" only once while using a loop via squash_actions is
deprecated. Instead of using a loop to supply multiple items and specifying `name: "{{ item
}}"`, please use `name: ['pygpgme', 'yum-utils']` and remove the loop. This feature will be
removed in version 2.11. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```
> Fix deprecation warning

- .travis.yml
- README.md
- defaults/main.yml
- files/gitlab-runner-wrapper.sh
- handlers/main.yml
- tasks/config-runner.yml
- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/line-config-runner.yml
- tasks/main.yml
- tasks/register-runner.yml
- tasks/section-config-runner.yml
- tasks/update-config-runner.yml
- tests/inventory
- tests/test.yml
This PR is quite a big change but was necessary for us at [`Fretlink`](https://github.com/fretlink/).
The 3 main changes are:
- allows to register multiple runners on the same instance
- allows to **remove** an existing runner with the `gitlab_runner_runners[i].state` value (`present` or `absent`)
- allows to change configuration for a runner (after registration) fixing #17 
- allow extra TOML options to be configured 
Adds a `extra_configs` key to a runner's variables to
allow custom TOML sections to be changed/added. 
The operation is **non-destructive**. Meaning that any existing
configuration option will **not** be removed if they already exist in
the `/etc/gitlab-runner/config.toml` file.
> Multiple runners, configurable runners and extra options

- README.md
- defaults/main.yml
- tasks/global-setup.yml
We use sentry in several of our projects. According to the [advanced config docs](https://docs.gitlab.com/runner/configuration/advanced-configuration.html), it is possible to set the dsn in the global config.
> Add sentry dsn to global config if it's defined

- tasks/register-runner.yml
warning are generated when trying to configure 
`cache_shared: true`
in yml file:
```
"stderr": "time=\"2019-06-10T07:58:21-07:00\" level=warning msg=\"boolean parameters must be passed in the command line with --cache-shared=true\"\ntime=\"2019-06-10T07:58:21-07:00\" level=warning msg=\"parameters after this may be ignored\"\n 
```
this fix makes `cache_shared` and `cache_s3_insecure` working correctly as boolean parameters
> fix boolean parameters

- defaults/main.yml
- tasks/config-runners.yml
- tasks/register-runner.yml
A couple of runner configuration values would fail if they were not set since the jinja was assuming they exist.
Also I made `/tmp` for the `gitlab-runner-wrapper.sh` script configurable since some systems disable executing on `/tmp` for security purposes, atleast this way it can be configured to something else by the user.
> Fix config bugs and add /tmp dir var

- tasks/config-runners.yml
- tasks/update-config-runner.yml
> Re-insert `[[runners]]` separator during assembly instead of manually

- tasks/global-setup.yml
The merge request adds a stage to the playbook that confirms that the `/etc/gitlab-runner/config.toml` file is present.  If it is absent, a blank file is created.  If it is already present, nothing happens.
See discussion on #55 
+ Delete `/etc/gitlab-runner/config.toml` from target machine and run playbook.  File should be created.
+ Run playbook again.  Task should return green OK.
> Ensure config.toml exists

- defaults/main.yml
- tasks/register-runner.yml
- tasks/update-config-runner.yml
I wanted to add builds_dir and cache_dir options, and realised that new options were not being reflected in the config.
The issue was with the `backrefs` configs set to true in `lineinfile`. When the entries didn't exist, the capture group was not available so Ansible wasn't adding them.
I also added `insertafter` so that the lines are after the main mandatory configurations.
Please let me know if it's ok. I love this role and wanted to contribute for a while.
Thanks!
> Fix update-config-runner | Add builds_dir and cache_dir options

- tasks/update-config-runner.yml
For now the extra `env_vars` passed in the role was only used at
registration step of the runner. This commit allows to *update* the
`environment` field of an existing runner configuration.
> config: allow environment field to be updated after registration

- tasks/main.yml
Otherwise the check produces an error when the token has been encrypted with ansible vault.
Resolves issue #67
> Force variable to be a string before checking its length

- .travis.yml
- defaults/main.yml
- files/gitlab-runner-wrapper-macos.sh
- handlers/main.yml
- meta/main.yml
- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/install-macos.yml
- tasks/main.yml
- tasks/register-runner.yml
- tests/test.yml
- vars/Darwin.yml
- vars/default.yml
This PR adds support for installing the gitlab CI runner on Mac OS machines (either the latest version or a specific version) with Travis CI tests to verify them on Linux and Mac.
Worth noting that the automated tests running in Travis CI do not actually do the registration; there is room for improvement by mocking the registration command and making sure it's being called when appropriate.
> Add macOS support

- README.md
- defaults/main.yml
- tasks/global-setup.yml
This PR enables `listen_address` feature in `gitlab-runner`. It results in opening port for Prometheus scraping the `/metrics` endpoint. Examples:
```
gitlab_runner_listen_address: ":9252"
gitlab_runner_listen_address: "localhost:9252"
```
Here's `gitlab-runner` documentation for the reference: [GitLab Runner monitoring](https://docs.gitlab.com/runner/monitoring/README.html).
Closes #75
> Enable listen_address for Prometheus metrics & monitoring.

- README.md
- tasks/register-runner.yml
Fixing a bug that slipped through the cracks in the PR #74 (the registration step is skipped in the Travis CI job).
Also updated the README with the new variable for the gitlab runner version, and the note about the package name.
> Fix macos runner registration step

- tasks/update-config-runner.yml
- tests/vars/default.yml
The config-parameters of the cache section were put into the `[runners]`-section, when using the `gitlab_runner.cache_*`-variables.
I had to use them because ansible complained that `.` was not allowed in Hash-Keys and therefore I could not use the `extra_configs`-key in `gitlab_runner_runners`-variable.
Fixes #72
> Add cache settings to correct sections

- tasks/update-config-runner.yml
When setting up a shell runner, I ran into a verification error:
```
FATAL: toml: cannot load TOML value of type map[string]interface {} into a Go string
```
Tracing it back, it appears that the [gitlab-runner is expecting a string](https://gitlab.com/gitlab-org/gitlab-runner/blob/c6bd01357946bc57cfcc490549d93fc26332dbc1/common/config.go#L304) for the `shell` attribute, but choking on `runners.shell` being a map. Since there
is no additional shell configuration, this patch makes the executor section conditional on the
executor type being something other than `shell`.
> Make executor section conditional

- tasks/register-runner-windows.yml
The registration script fails when trying to use one of the ssh option without a value.
> make ssh section conditional in windows

- tasks/Unix.yml
Need to run the `List configured runners` and `Check runner is registered` as the privileged user so that it picks up the global config.toml and not the non-existent one in the user's home directory.
This addresses issue #89
> Run list and verify methods as privileged user

- tasks/global-setup-windows.yml
- tests/vars/Windows.yml
Task "(Windows) Add listen_address to config" was using a fixed path for the runner config file
> Fix runner config path on Windows listen_address

- tasks/register-runner-windows.yml
In order to make s3 cache authentication through IAM instance profile,
s3 access key and secret key were converted to optional parameters
> Making s3 access key and secret key as optional

- tasks/update-config-runner-windows.yml
- tests/vars/Windows.yml
S3 cache directives were out of order on the runner `config.toml`, now we are applying the same regex to configure s3 cache on Windows and Linux.
> Fix windows cache s3 config order

- defaults/main.yml
- tasks/update-config-runner.yml
- tests/vars/default.yml
It seems that now the default gitlab-runner configuration comes with GCS cache enabled. I haven't ben able to really test this, as I don't use GCS, and I just wanted to get rid of the configurations.
I have only been able to do some smoke tests (setting vars and confirm that the confgs appear in config.toml), other than that, this could be considered as untested.
Thanks!
> Allow GCS cache configuration

- tasks/update-config-runner.yml
This PR fixes s3 section in config.toml
- set cache_s3_server_address as optional and generate runners.cache.s3 when cache is *s3*. The default server is AWS s3.
- mutex the "BucketName" tasks as both gcs and s3 use "^\s*BucketName" regexp
> Fix s3 cache section

- README.md
- tasks/Unix.yml
- tasks/Windows.yml
Turns out you already accounted for a token per runner with this line:
`--registration-token '{{ gitlab_runner.token|default(gitlab_runner_registration_token) }}'`
in both Unix and Windows.  This PR updates the conditional register-runner.yml to look at the specific or the global token.  It also updates the README to indicate that this is an option.
Closes #99
> Allow registration token per runner

- README.md
- tasks/register-runner.yml
- tasks/update-config-runner.yml
add support for setup an autoscaling Gitlab Runner on AWS with docker-machine
including:
- feat: make off_peak in runner_machine settings optional
- fix: add replace function to "Set runner executor section" task
- docs: update README with var descriptions and sample vars/main.yml
resolves issue #85
----
#
> feat: provide support for autoscaling setup on AWS with docker-machine

- .travis.yml
- defaults/main.yml
- files/gitlab-runner-wrapper-macos.sh
- files/gitlab-runner-wrapper.sh
- handlers/main.yml
- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/register-runner.yml
- tasks/update-config-runner.yml
- tests/files/mock_gitlab_runner_ci.py
- tests/test.yml
- tests/vars/Windows.yml
- tests/vars/default.yml
- vars/Darwin.yml
- vars/Debian.yml
- vars/RedHat.yml
- vars/Windows.yml
- vars/default.yml
- vars/main.yml
There were some permission issues when setting up on mac because of the difference between user mode and system mode. This PR makes the distinction between the two clear, without changing the defaults for Linux.
Also improves tests by checking that the registration step actually executes successfully against a mock server.
(Those were some old changes that I rebased on the latest master, but it seems there should not be any major conflicts)
> Support system-mode and user-mode

- README.md
- defaults/main.yml
New coordinator URL value taken from https://docs.gitlab.com/runner/register/#gnulinux
> Small readme improvements and fix default coordinator URL

- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/register-runner.yml
I'm using the default setting `gitlab_runner_system_mode: yes` and installing to Ubuntu and CentOS runner nodes with Ansible 2.8. Tasks that have `become: gitlab_runner_system_mode` directive fail with errors such as `Operation not permitted` or `file is not readable`, indicating that `become` is not working as intended.
The fix is to expand the `gitlab_runner_system_mode` variable in `become` directives.
> Fix become directives

- defaults/main.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
Maybe I miss something but there is an option clone_url for:
Overwrite the URL for the GitLab instance. Used if the Runner can’t connect to GitLab on the URL GitLab exposes itself.
from: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
> Add clone_url option

- defaults/main.yml
env_vars correspond to the environment configuration that is used in the build environment not registration command.
> main.yml: Correct minor documentation error

- tasks/config-runners-windows.yml
Hi,
thank you for the great work!
We're running into a Windows-only issue when running `ansible-playbook --check` (the error does not happen without `--check`):
```
TASK [riemers.gitlab-runner : include] ****************************************************************************************************************************************************************************
skipping: [build-windows]
TASK [riemers.gitlab-runner : (Windows) Remove runner config] *****************************************************************************************************************************************************
skipping: [build-windows] => (item={'shell': 'powershell', 'cache_dir': 'C:\\gitlab-runner\\cache', 'tags': ['windows', 'powershell'], 'run_untagged': False, 'executor': 'shell', …
```
> Fix 'path does not exist' error when using Windows + --check.

- tasks/section-config-runner-windows.yml
- tasks/update-config-runner-windows.yml
Hi,
when targeting Windows, there is a Linux-only include that cause the "Ensure section exists" task to run on the Windows target. Which of course simply stalls and never works.
This PR fixes this issue.
> Fix wrong include for section-config-runner on Windows.

- tasks/update-config-runner-windows.yml
Hi,
the generated `config.toml` is missing the `[[runners]]` section because:
* its removed by the `split()` [here](https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/config-runners-windows.yml#L13)
* its never reprinted in the temporary file created for each runner
As a result, the call to `gitlab-runner.exe verify` fails with the following error:
```
FATAL: Near line 32 (last key parsed 'runners'): Key 'runners.custom_build_dir' has already been defined.
```
This PR fixes that issue.
> Fix missing [[runners]] section on Windows.

- defaults/main.yml
- tasks/install-windows.yml
Hi,
per the following documentation:
https://docs.gitlab.com/runner/install/windows.html#troubleshooting
the `--user` and `--password` options can be specified to install the Windows service for a specific user account.
This PR adds two new variables to do just that:
* `gitlab_runner_windows_service_user`
* `gitlab_runner_windows_service_password`
This is important because running with the `SYSTEM` account has limitations, especially if you rely on the `virtualbox` executor: the base images won't be found.
> Add support for Windows user account when installing the service.

- tasks/register-runner.yml
Use s3 cache without explicit cache_s3_access_key in order to use IAM
instance profiles to authenticate on s3.
> Make cache_s3_access_key optional

- defaults/main.yml
- tasks/update-config-runner.yml
This adds the ability to specify the networking mode of the container. I have intentionally kept the default in this role the same as the default in Gitlab/Docker.
It is mentioned [here](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersdocker-section) although undocumented.
> Adds the ability to specify the container network

- tasks/Unix.yml
PROBLEM:
global option will is overwritten after runner need registration again, or if config file was deleted
HOW TO REPLCIATE:
- deregister and remove runner from gitlab without removing actual runner 
- rerun playbook again 
- check that global options like concurrency or listen-address is removed from config
FIX:
move setting of global option after registration of worker
> fix removing global options when need to re register runner

- tasks/install-debian.yml
First attempt to fix #137 
I've created a conditional on `when: ansible_distribution_release in ["buster", "focal"]`
If you want to be more specific we can make it conditional on `ansible_distribution` and `ansible_distribution_release`.... or other OS data. 
If future releases of both distros are going to create `.bash_logout` then we might want to move the list of relevant releases into `vars/Debian.yml`
Feedback welcome!
> Remove .bash_logout for both Debian Buster and Ubuntu Focal

- README.md
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
Issue #145.
For users having multiple Gitlab instances (such as during migration between systems), it is highly beneficial to connect the same runner instance to multiple Gitlabs. Currently, only a single global coordinator url is supported.
This PR enables configuring runner-specific url in vars and using that when registering the runner.
> Support runner-specific coordinator url

- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
- tests/vars/Windows.yml
- tests/vars/default.yml
Not to be confused with the shell executor, this configures the shell that will be used to execute the script steps inside running jobs. Mostly useful for windows, where people might want either cmd/powershell, or bash for more portable build scripts.
See https://docs.gitlab.com/runner/shells/.
Let me know if there's anything weird in this.
> feat: configure runner shell if defined

- README.md
- defaults/main.yml
- tasks/install-debian.yml
- tasks/install-redhat.yml
Add the ability to skip the repository installation on servers isolated from internet and/or behind a proxy repository such as Nexus or Artifactory.
A repository with all the required packages should be configured before using this option.
By default, no behavior changes.
> Add an option to skip the repository installation

- handlers/main.yml
- tasks/install-redhat.yml
- vars/RedHat.yml
- vars/default.yml
Restarting a runner without `SIGQUIT` will cause the runner to immediately cancel all jobs, and restart, which is quite undesirable. Instead, on systemd based systems (only implemented for Red Hat derivatives currently), we should configure systemd to use `SIGHUP` to reload when the configuration changes, and `SIGQUIT` before stopping/restarting to ensure gitlab waits for jobs to complete before stopping. The timeout to wait before forcefully killing the process to restart can be configured with `gitlab_runner_timeout_stop_seconds`.
> Support reloading gitlab under systemd instead of restarting

- tasks/install-debian.yml
- tasks/install-redhat.yml
- tasks/systemd-reload.yml
- vars/Debian.yml
The debian runner installation also has a compatible systemd unit for
reloading. This moves systemd-reload setup into a new file and enables
it for debian and redhat.
> Support systemd reloading on debian too

- README.md
- tasks/line-config-runner-windows.yml
- tasks/line-config-runner.yml
The problem was in line-config-runner-windows.yml with regexp.
In PR https://github.com/riemers/ansible-gitlab-runner/issues/153 We have added to_json to the "line" parameter and parameters stopped to match regexp:
Before:
```
[runners.docker]
cpus = "4"
volumes = ["/certs/client", "/cache"]
privileged = true
memory = "8g"
```
After:
```
[runners.docker]
"cpus" = "4"
"volumes" = ["/certs/client", "/cache"]
"privileged" = true
"memory" = "8g"
```
I've fixed regexp to match with lines.
-------------
Also, updated cache section update in Readme.
The previous one doesn't match with a code.
> Fix - Running role second time corrupts config.toml

- .gitignore
- .travis.yml
- README.md
- handlers/main.yml
- tasks/systemd-reload.yml
- tests/travis-bootstrap-ansible.ps1
- tests/vars/default.yml
TL;DR:
* Removing checksum tests of Ubuntu 1804 choco package for the Windows tests, as the wsl choco package for ubuntu 1804 is broken, pending pull request https://github.com/bcurran3/ChocolateyPackages/pull/238
* Minor edit of README.md, to use become: true
* The suggested changes will fix the issues we have in Travis CI at the moment
* Fixing some typos in the yaml files
Longer story:
This pull request will not do much, other than take a step forward to fix the broken ci/cd tests, and a minor change to the README docu. The use of `remote_user: root` is not applicable to most environments, where `root` is not allowed to ssh into a system.
Note the changed `gitlab_runner_system_mode: yes` in the `tests/vars/defaults.yml` file, which was breaking the tests, as it broke quite a few things …
> * Fixing broken tests

- tasks/global-setup.yml
- tasks/register-runner-container.yml
- tasks/register-runner.yml
In our environment we use some gitlab-runner config parameters that are not yet in this ansible role. Example:
```
log_format = "json"
[runners.docker]
disable_cache = false
dns_search = ["us-east-2.somedomain.tld"]
oom_kill_disable = true
```
This PR aims to add those options.
> extra runner config options

- tasks/install-redhat.yml
This reverts commit 55a423f84bed801f17ff79d2a56e84dd32761022.
There is no reason to enforce the el7 packages on el8 anymore, as el8 is now [fully supported](https://docs.gitlab.com/13.9/runner/install/linux-repository.html).
It also allows for overriding the el and dist environment variables, which is necessary when using this role on e.g. Amazon Linux
> Revert "install gitlab-runner on el8 from el7 repo"

- tasks/global-setup.yml
Based on feedback here:
https://github.com/riemers/ansible-gitlab-runner/pull/165 
- add default log format as type 'runner'
- Change the line placement to beginning of file as some users do not specify 'listen_address'
> log_format placement

- defaults/main.yml
This PR adds default value for `log_format` option. It will remove [this error](https://github.com/riemers/ansible-gitlab-runner/pull/165#issuecomment-787448997) if value is not set in vars.
> Add default value for gitlab_runner_log_format option

- tasks/global-setup-windows.yml
This should fix the deployment to windows machines. 
(https://github.com/riemers/ansible-gitlab-runner/pull/160#issuecomment-795876599)
Developed with assumptions as I do not have a windows machine available to test with.
> bugfix: replaced lineinfile for win_lineinfile for windows deployment

- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
to enable the passthrough of specific devices (like the fuse device) to the docker runner, i adapted the volumes part. besides the problems i already had in the current upstream master version (https://github.com/riemers/ansible-gitlab-runner/issues/59#issuecomment-822018779) i have tested it successfully.
> added docker_devices

- defaults/main.yml
- tasks/Container.yml
- tasks/register-runner-container.yml
By default the docker_container module uses the first network in `docker network list`. Often this is the bridge network, which is inferior to custom networks (see [docs.docker.com](https://docs.docker.com/network/bridge/)) and also is unable to lookup containers on the same host (The default Bridge-Network takes the DNS Configuration of the host, while the custom networks are able to lookup the containers via DNS). 
As it would be possible to enter several networks for a runner, with the `networks` parameter, i think this is overly complex, since it MUST be configured since no sane default is usable.
Instead I added a parameter for `network_mode` [docs.ansible.com](see (https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-network_mode …
> added possibility to define a network for the containers

- defaults/main.yml
vars/default.yml is not always loaded, since https://github.com/riemers/ansible-gitlab-runner/blob/5caa92463e00a8b9ed9fe0f94d2d56230fd4a79b/tasks/main.yml#L2-L11 does not load it, if a distribution or os_family is found.
Since these variables are independent of any distribution, they should go to defaults/main.yml
If they are not loaded or not defined https://github.com/riemers/ansible-gitlab-runner/blob/5caa92463e00a8b9ed9fe0f94d2d56230fd4a79b/tasks/Container.yml#L67 fails with `variable undefined`
IMHO vars/default.yml could be completely removed, but I don't know if there are any edge-cases where no distribution or os_family is found and the include_vars fails.
> move default vars to default/main

- defaults/main.yml
- tasks/main.yml
- tests/test.yml
- vars/default.yml
Those variables were copied to `vars/main.yaml` in this PR: https://github.com/riemers/ansible-gitlab-runner/pull/179
We couldn't get the container installation to work because the `gitlab_runner_container_install` was always overwritten by `vars/main.yaml`. Deleting it helped and we can now use it like described in the [docs](https://github.com/riemers/ansible-gitlab-runner#example-playbook).
> remove vars/default.yaml

- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
For users having multiple Gitlab instances (such as during migration between systems), it is beneficial to connect the same runner instance to multiple Gitlabs. 
This PR builds on https://github.com/riemers/ansible-gitlab-runner/pull/146, adding support for the coordinator-specific URL in config-building too, not only registering. Basically the previous PR is incomplete and this is required on top.. Not sure how I managed to make it work with the previous change only.
Related issue: https://github.com/riemers/ansible-gitlab-runner/issues/145.
> Fix runner-specific coordinator url in upate-config-runner

- tasks/Container.yml
Previously, running the `--check` mode was deleting the `gitlab_runner_container_name` container leading to unexpected downtime. This change also shortens the downtime during deployments.
> namespace container names running in the check mode

- tasks/global-setup-windows.yml
- tasks/global-setup.yml
closes https://github.com/riemers/ansible-gitlab-runner/issues/192
line with  `listen_address` in `session_server` section should have at least one  `space` symbol
btw. not sure about regex `capturing group - ()`  usage, it has been used inconsistently in this role.
> Fix listen_address regex overlap

- README.md
I needed to change the "gitlab_runner" block in the variables file to "gitlab_runner_runners" to match /defaults/main.yml
> Updated README to match /defaults/main.yml

- tasks/update-config-runner.yml
When not defining any `cache_type`, an empty cache section is created leading
to further configuration being misplaced:
```toml
[[runners]]
[...]
[runners.docker]
volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache", "/cache-ci:/cache-ci:rw"]
[runners.cache]
image = "alpine:latest"
privileged = false
[runners.docker.services_tmpfs]
"/var/lib/mysql" = "rw,noexec"
```
> fix: empty cache section

- tasks/Unix.yml
- tasks/install-arch.yml
- vars/Archlinux.yml
Tested it with the following config and everything worked as expected:
```yml
---
gitlab_runner_coordinator_url: https://XXX.org
gitlab_runner_registration_token: 'XXX'
gitlab_runner_concurrent: 4
gitlab_runner_listen_address: '0.0.0.0:9252'
gitlab_runner_runners:
- name: 'arch-box1'
executor: docker
docker_image: 'ubuntu:20.04'
tags:
- docker
- arch-box1
docker_volumes:
- "/var/run/docker.sock:/var/run/docker.sock"
- "/cache"
- "/opt/ccache"
- "/builds"
env_vars:
- CTEST_PARALLEL_LEVEL=16
- OMP_NUM_THREADS=1
```
> Minimal support for Arch Linux.

- README.md
- tasks/config-runners-windows.yml
- tasks/update-config-runner-windows.yml
PR to fix #194 
After playbook run, the config.toml gets an extra `[[runners]]` tag, which registers a empty extra runner.
**Before**
```
[[runners]]
[[runners]]
name = "bc-gr-08_pt2d"
limit = 0
output_limit = 4096
```
and if you run the playbook again it will add additional blankspaces for each time you run it.
```
[[runners]]
[[runners]]
name = "name"
limit = 0
output_limit = 4096
```
**After**
```
[[runners]]
name = "name"
limit = 0
output_limit = 4096
```
> Making the config-runner-windows idempotent & Removing duplicate runner tag/block

- defaults/main.yml
- tasks/Container.yml
- tasks/config-runner-container.yml
- tasks/config-runner-windows.yml
- tasks/config-runner.yml
- tasks/config-runners-container.yml
- tasks/config-runners-windows.yml
- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/install-windows.yml
- tasks/line-config-runner-windows.yml
- tasks/line-config-runner.yml
- tasks/section-config-runner-windows.yml
- tasks/section-config-runner.yml
- tasks/systemd-reload.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
- When you have a large config file with many options, running this role looks like loop. I've added progress indicators in names of tasks. It looks like:
`TASK [ansible-gitlab-runner : conf[2/5]: runner[1/4]: section[1/2]: line:[2/6]: Modify existing line]`
- Also add option gitlab_runner_show_config_diff to show diff, when new config replaces old one. But it doesn't work for me, probably because of old version of assemble module.
- In the end I have fixed linter warnings and errors (but add skipping for two of them)
> Add counters in names of tasks, whose are called from loops

- tasks/section-config-runner-windows.yml
- tasks/section-config-runner.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
Quick PR to quiet down ansible.
> Include: directive is being deprecated, change to include_tasks:

- tasks/update-config-runner.yml
When I run the latest version of the ansible role, I get incorrect output in the configuration file when using 'dns_search'.
This leads to an incorrect docker resolv.conf.
As with the 'dns' option, the entry in config.toml should be adjusted.
Ansible Variable:
```
docker_dns_search:
- "example.com"
```
Result config.toml:
`dns_search = ["[example.com]"]`
Desired config.toml:
`dns_search = ["example.com"]`
> Rewrite docker dns search option

- tasks/global-setup.yml
- tasks/register-runner.yml
The permissions of /etc/gitlab-runner are set to 700 by the
gitlab-runner [post-install script][1]. Use these permissions for the
directory in the Ansible role as well.
Fixes #216.
[1]: https://gitlab.com/gitlab-org/gitlab-runner/-/blob/b57e6fbd6311ef8eec01dd03e171ea3a61b4ef4c/packaging/root/usr/share/gitlab-runner/post-install#L41
> Fix permissions of gitlab-runner config file dir

- meta/main.yml
The readme stats that ansible version 2.7 or higher is required. However, this file still said it was version 2.0
> update minimum ansible version requirement

- defaults/main.yml
This commit adds a role variable available to use to specify docker mount path with {{ gitlab_runner_container_mount_path }}. Extends fix #226
> Add docker mount variable for fix #226

- tasks/update-config-runner.yml
- vars/Darwin.yml
Fix gitlab_runner_download_url for MacOS arm64 architecture and small fix in logic.
> Fix gitlab_runner_download_url for MacOS arm64 architecture

- tasks/install-macos.yml
When the folder '/usr/local/var/log' doesn't exist gitlab-runner fails to start on M1 architecture.
On Intel it works fine.
Related issue:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28136
> Create gitlab-runner log directory on MacOS arm64

- tasks/Unix.yml
To list runners on MacOS one should use the same user mode as everywhere
else.
> fix: list runners on Mac

- tasks/line-config-runner-windows.yml
- tasks/line-config-runner.yml
the keys for extra-config-options should not always be in quotes. this happens because every line is filtered with to_json.
now quotes (to_json) will only apply if the key contains a dot and is neccessary because of the "runners.docker.sysctls" section.
> Config property keys not always in quotes with to_json

- tasks/register-runner.yml
gitlab-runner register lacks an option to accept untrusted certificates. In dev environments this can sometimes be hand. This PR works around the issue by downloading the cert of the gitlab server and putting it in the file reference by the var "tls_ca_file" when the var "force_accept_gitlab_server_self_signed" is true.
> Option to force accept self signed cert from gitlab server.

- defaults/main.yml
Without it an error is raised `'force_accept_gitlab_server_self_signed' is undefined`
```json
{
"msg": "The conditional check 'force_accept_gitlab_server_self_signed' failed. The error was: error while evaluating conditional (force_accept_gitlab_server_self_signed): 'force_accept_gitlab_server_self_signed' is undefined\n\nThe error appears to have been in '/root/.ansible/roles/riemers.gitlab-runner/tasks/register-runner.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Accept gitlab server self signed cert as valid CA\n  ^ here\n"
}
```
> Add default value for force_accept_gitlab_server_self_signed

- defaults/main.yml
#243 added an option to allow self-signed certificates.
This caused all existing playbooks to fail because they missed a value for `force_accept_gitlab_server_self_signed`.
#244 tried to add a default value for `force_accept_gitlab_server_self_signed`.
Unfortunately, the change introduced invalid YAML:
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)
Syntax Error while loading YAML.
could not find expected ':'
The error appears to be in '/root/.ansible/roles/riemers.gitlab-runner/defaults/main.yml': line 73, column 1, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
^ here
```
This pull request fixes the syntax error by setting the …
> Fix: Syntax error "could not find expected ':'"

- tasks/register-runner.yml
- tasks/update-ca-bundle.yml
- When parameter `force_accept_gitlab_server_self_signed` is set to true the self signed cert of the gitlab server is stored in the location of `tls_ca_file` parameter (previous change)
- This change will run update of the CA-store too so that when `tls_ca_file` is the location for local certificate approval (for example /usr/local/share/ca-certificates on ubuntu), all https clients that use the "system CA-bundle" will accept the gitlab server certificate
- This is necessary for CI/CD-pipelines to work properly when runner needs to clone code from the gitlab server over https
- Should work on RedHat/CentOS/Ubuntu/Debian . Tested on Ubuntu 22.04
> Update CA-bundle after (optionally) accepting self signed cert from gitlab server

- tasks/install-debian.yml
This freezes the installed GitLab Runner version on Debian/Ubuntu hosts when we specify a version from in the role variables. This ensures that running a packages upgrade on the machine does not update the GitLab Runner to a newer version, and keep it at the version installed by the role instead.
This also allows downgrading to a version specified from the role when the one installed on the machine is greater.
The drawback is that the used `allow_downgrade` option from the built-in apt module to achieve this is only available from Ansible version 5 and onwards (Ansible-core 2.12+)
I was tempted to also update the `min_ansible_version` and README to specify this, however since this only impacts Debian/Ubuntu hosts, I was not too sure about bumping the required version only for a single …
> Pin the installed version on Debian/Ubuntu and allow downgrades

- tasks/Container.yml
- tasks/Unix.yml
- tasks/Windows.yml
- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
Hi,
it seems that there is an issue when we have a simple situation like this
```
Runner1
* ExecutorA - valid
* ExecutorB - deleted (this executor was deleted in the Gitlab UI by removing it in the runner tab)
```
When I let this role run again, the result is very strange and the following will happen:
```
* ExecutorA is not longer available on the runner - in the UI the executor is then marked as offline
* ExecutorB - valid
```
Expected output would be:
```
* ExecutorA - valid
* ExecutorB -valid
```
I narrowed it down to have something todo because the list of runners is queried and when at least one runner is in a bad shape (deleted) then the whole `config.toml` is deleted, but the valid runner is then not again registered.
---
This MR fixes this so that deleted executors don't affect …
> Fix problem with deleted runners

- defaults/main.yml
Document `docker_wait_for_services_timeout` variable.
I was setting this option using `extra_configs` because I couldn't find a dedicated variable to set. However, doing so will actually cause a change on every run because the default will be re-written just for the extra config to correct it again.
> docs: document docker_wait_for_services_timeout

- defaults/main.yml
- tasks/update-config-runner.yml
- templates/config.runners.docker.services.j2
as per issue https://github.com/riemers/ansible-gitlab-runner/issues/118 I've create this PR on behalf of [marcelbrueckner](https://github.com/marcelbrueckner)
> add runner.docker.services support

- tasks/update-config-runner.yml
This pull request aims to avoid corruption of the `config.tml` file with the addition of an unwanted block `[runners.cache.azure]` or `[runners.cache.s3]`.
> Fix corrupt cache in config.toml

- tasks/install-debian.yml
Use `cache_valid_time` to ensure we refresh when necessary, but avoid needlessly doing so on every run.
Fixes https://github.com/riemers/ansible-gitlab-runner/issues/259
> Refresh apt cache prior to running repo installation script

- tasks/install-debian.yml
The role unholds and holds the gitlab-runner version in Debian. Idempotence always reported the holding as changed.
> fix debian idempotence

- README.md
- defaults/main.yml
- tasks/Container.yml
- tasks/Unix.yml
- tasks/Windows.yml
- tasks/main.yml
- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
Hi, I know this PR is quite extreme but maybe we use it as a discussion base:
From a high level, this role does
* Registering runners (Windows, Linux, Container)
* Apply config changes to the `config.toml`
We have a lot of VMs where each of them contains quite some runners (with different tags and settings).
Because of that, this role runs for ages even if no updates are done. Actually it runs that long that it exceeds the
default Ansible timeout of 1 hour.
Furthermore we play around with tags quite often, but this is problematic because this role currently doesn't support tag updates (because tags are not reflected in the `config.toml`
To overcome the issues above, I changed the way this role handles config updates. 
* Whenever a runner is registered, the registration command (with …
> Apply updates to runners by untegister and register them again

- defaults/main.yml
- tasks/update-config-runner.yml
When the (self-hosted) gitlab instance requires the clients to authenticate when connecting via HTTPS, it is necessary to define certificate and key files for the runners too to be used.
See: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
> Add mutual TLS (mTLS/client side TLS) options to the configuration

- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
When `register_runner_cmd` is put together to be run the `>` mode of Yaml puts a newline at the end of the string. This breaks the command.
Using `>-` removes this newline.
> Remove spurious newline in middle of command

- tasks/register-runner-windows.yml
When running the registration command with a `pre-build-script` the argument parameter is getting over-escaped, e.g.:
```
--executor 'docker-windows'  --limit '0' --output-limit '20480' --locked='False'    --pre-build-script \"cmd /c \"echo
```
Because my command uses redirection this then feeds into the ansible command and produces an error.
Changing to use single quotes for the command arg avoid this, producing:
```
--executor 'docker-windows'  --limit '0' --output-limit '20480' --locked='False'    --pre-build-script 'cmd /c \"echo
```
I'm not sure if it's the best fix, maybe some escaping filter should be used instead.
> Avoid over escaping

- tasks/register-runner-windows.yml
When running the unregister command the runner is not detected because gitlab-runner defaults to local user config rather than the central config location.
The list commands already do this.
> Change directory before unregistering

- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
This commit separates the inclusion of scripts from the registration command.
ref: https://github.com/riemers/ansible-gitlab-runner/issues/270
> Decouple scripts from registration command

- README.md
- defaults/main.yml
- tasks/main-container.yml
- tasks/main-unix.yml
- tasks/main-windows.yml
- tasks/main.yml
- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/unregister-runner-if-not-longer-configured.yml
- tasks/unregister-runner.yml
When a runner executor is registered in gitlab but not longer configured in ansible, currently the executor was untouched because it it not known by this role. Now there is a new flag whcih controls if such executors should be unregisterd, in case they are not longer configured in ansible.
> Remove not longer configured runners

- defaults/main.yml
- handlers/main.yml
- tasks/list-configured-runners-windows.yml
- tasks/main-windows.yml
- tasks/register-runner-windows.yml
- tasks/update-config-runner-windows.yml
It seems the current implementation breaks if there are no configured runners, this brings the window configuration in line with the other Unix configurations.
It seems to work on my side when testing just this included file.
> Fix deploying to Windows machines

- defaults/main.yml
- tasks/main.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
- tasks/validate-runner-config.yml
* Add support for `post_get_sources_script` in the runner config.
* The `pre_clone_script` config option has been deprecated for a while now and is replaced by `pre_get_sources_script`.
See GitLab 16.2 docs: [Advanced Configuration / The [[runners]] section](https://docs.gitlab.com/16.2/runner/configuration/advanced-configuration.html#the-runners-section)
> Add support for `post_get_sources_script`, replace deprecated `pre_clone_script` with `pre_get_sources_script`

- defaults/main.yml
- tasks/config-runner.yml
- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/main-unix.yml
- tasks/update-config-runner.yml
Ensure no secrets will leaks when running `ansible`.
Add a new option that is not defined by default, adding this option will mute a lot of config tasks output.
⚠️ This setup is only done for unix runners, I don't have any windows machine to test
- add a S3 cache section with credentials
- run `ansible-playbook` with `-vvvv` arg
- look for credentials in output 👀 💥 
- define `gitlab_runner_no_log_secrets: yes` and run again
- look for credentials in output 👀 ✅ 
Thanks for your role it does exactly what I was looking for !
I just need this feature to use it for production purposes.
> Add a `gitlab_runner_no_log_secrets` option to prevent secret leaks

- tasks/register-runner-windows.yml
Using version 1.6.54. Upgrading to latest didnt work out of the box (will look into that later).
When using the role, the variable used on the two changed lines contains a newline character. Which breaks the runner registration. Calling trim like so fixes it. But Im curious why no one else has run across this, feels like it should never work or work all the time.
```
$ pipenv requirements
-i https://pypi.org/simple
ansible==8.3.0
ansible-core==2.15.3 ; python_version >= '3.9'
cffi==1.15.1
cryptography==41.0.3 ; python_version >= '3.7'
importlib-resources==5.0.7 ; python_version < '3.10'
jinja2==3.1.2 ; python_version >= '3.7'
jmespath==1.0.1
markupsafe==2.1.3 ; python_version >= '3.7'
packaging==23.1 ; python_version >= '3.7'
pycparser==2.21
pyyaml==6.0.1 ; python_version >= '3.6' …
```
> Add trim to register_runner_cmd

- tasks/install-macos.yml
Hey, it's been a while :)
I do have a small fix for the MacOS part of the role. If fails repeatedly because ansible cannot override the GitLab Runner executable as it is owned by `root`. Replicating the behaviour from the `download` section and using `become` fixes the issues and seems to be the right approach.
Cheers,
Matthias
> Fix Download and update gitlab-runner on MacOS

- tasks/install-debian.yml
fix(install-debian.yml): add condition to unhold GitLab Runner version only if 'gitlab-runner' package is installed
Fixes #301
> fix(install-debian.yml): add task to gather package facts before unholding GitLab Runner version

- .github/workflows/ansible.yml
Perhaps a good idea to run ansible-lint in the CI to catch potential issues
> fix: run ansible-lint in ci

- defaults/main.yml
- tasks/global-setup.yml
This _should_ add all of the necessary bits for adding log_level to the config.toml
> Add log level

- defaults/main.yml
- tasks/global-setup-windows.yml
- tasks/global-setup.yml
Add support to set `check_interval` in the global config section.
> `check_interval`: Defines the interval length, in seconds, between the runner checking for new jobs.
> The default value is `3`. If set to `0` or lower, the default value is used.
See https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section
This defaults to `0` which matches the default auto-generated config, and simply causes GitLab runner to use its default value (see above). So this shouldn't cause any change in behaviour for existing users of this role.
> Add support for setting `check_interval`

- defaults/main.yml
- vars/Archlinux.yml
- vars/Debian.yml
- vars/RedHat.yml
There's not really a reason to have different values for each os. This unifies the default to be 7200 and allows overriding it (because it's now just a default var). I use the override for hosts with long running ci jobs.
> vars: unify and move gitlab_runner_timeout_stop_seconds to defaults

- .gitignore
- README.md
- tasks/update-config-runner.yml
- templates/config.runners.machine.autoscaling.j2
I created this pull request because I could not configure the runners.machine.autoscaling section for docker-machine correctly. The reason for this is the double use of variables with the same name in the two sections runners.machine and runners.machine.autoscaling, such as IdleCount or IdleTime.
I have omitted the deprecated options.
> add runners.machine and runners.machine.autoscaling support

- tasks/line-config-runner.yml
Fixing #302 
The configuration of a docker tmpfs option contains slashes and must be converted to json.
https://docs.gitlab.com/runner/executors/docker.html#mount-a-directory-in-ram
> Add support for docker tmpfs options

- README.md
- meta/main.yml
- tasks/install-debian.yml
- `allow_downgrade` has been added in ansible-core 2.12
- `allow_change_held_packages` has been added in ansible-core 2.13
- Fix issue #327
> fix: impossible to change debian package version which is on the apt hold list

- tasks/register-runner.yml
- tasks/update-config-runner.yml
Adds support for ```--docker-allowed-pull-policies``` when registering the runner, as documented here: https://docs.gitlab.com/runner/executors/docker.html#allow-docker-pull-policies
> add support for 'gitlab-runner register --docker-allowed-pull-policies' 

- defaults/main.yml
- tasks/update-config-runner.yml
- templates/config.runners.feature_flags.j2
I couldn't configure runners.feature_flags, so I added support for feature flags which are described here: 
https://docs.gitlab.com/runner/configuration/feature-flags.html#available-feature-flags
Other fixes:
* fixed some linting and bool values for consistency
* only add machine section if machine_MachineOptions is set
If I should split this PR into separate ones, please let me know.
> add config section feature_flags

- tasks/register-runner.yml
Fixes https://github.com/riemers/ansible-gitlab-runner/issues/236
> Fix registering runner when docker_tlsverify is set

- README.md
- defaults/main.yml
- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
To support "--token" option: runner register --token glrt-XXXXXXXX
New workflow https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html
> Add runner registration with runner auth token

- tasks/list-configured-runners-unix.yml
When I used the role to deploy Gitlab runners with the new workflow (Gitlab runner version 17.2.1) I noticed that the step `Create list of configured runners` displayed the runner token despite the `gitlab_runner_no_log_secrets` option being set.
This PR adds the `no_log` option to this step to prevent the output of the runner token.
Example before patch:
```
TASK [riemers.gitlab-runner : Create list of configured runners] ***************************************************************************************
skipping: [terraform-ci] => (item={'arch': 'amd64', 'level': 'info', 'msg': 'Runtime platform', 'os': 'linux', 'pid': 15288, 'revision': '9882d9c7', 'time': '2024-08-02T08:56:14Z', 'version': '17.2.1'}) 
skipping: [terraform-ci] => (item={'ConfigFile': …
```
> Add `gitlab_runner_no_log_secrets` to list of configured runners

- tasks/install-macos.yml
already defined in line 68. and this can break interpreters for yaml...
> macos: remove duplicate `become`

- tasks/global-setup-windows.yml
This fixes a regression introduced in 62ec42ff causing the following error on Windows: "The powershell shell family is incompatible with the sudo become plugin".
See https://github.com/riemers/ansible-gitlab-runner/pull/315#issuecomment-2279144411 for background discussion.
> Windows: Remove become to fix provisioning on Windows

- tasks/register-runner.yml
sadly i have to report the current version throws:
```
"set -o pipefail\nopenssl s_client -connect some.company.portal.com:443 -showcerts </dev/null 2>/dev/null |\nsed -e '/-----BEGIN/,/-----END/!d' | tee /usr/local/share/ca-certificates/gitlabcert.crt >/dev/null\n"
```
I guess this fixes it (not tested yet)
> fix self-signed shell

- README.md
Hi there, 
this Merge Request aims to clarify the documentation regarding the use of the `gitlab_runner_registration_token`. I initially understood the current wording, `it is recommended to specify a token for each runner` as a suggestion rather than a requirement. The clarification here highlights that specifying a token for each runner is required, not just recommended, when `gitlab_runner_registration_token_type` is set to `authentication-token`.
An alternative proposal would be allowing the global gitlab_runner_registration_token to be used with the --token command by default in the same way it works with the --registration-token option. That would simplify the process for registering multiple runners, as in the [current GitLab …
> docs: Clarify registration_token requirement

- tasks/register-runner.yml
The command line argument for disabling the docker cache was passed twice, with the first one incorrectly adding `True` as a value to the argument. This commit removes the incorrect argument leaving only the valid one
Fixes #351
> Remove additional `docker-disable-cache` argument

- defaults/main.yml
- vars/Windows.yml
Under Windows, it is a common practice to use different partitions or hard disks to prevent applications from overloading the main hard disk and crashing the system. GitLab Runner is also a good candidate to fill up the disk and crash the computer. Therefore, it would be helpful to install it on a separate hard disk, but at the moment this is not possible due to variable precedence.
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence
Therefore, the installation directory should be moved to the defaults and then this can be changed in the inventory for each host or globally.
> Feature: Allow overwriting of 'gitlab_runner_install_directory'

- defaults/main.yml
- requirements.yml
- tasks/register-runner.yml
- vars/Archlinux.yml
- vars/Debian.yml
- vars/RedHat.yml
This is a fix for importing the gitlab server cert on linux systems. This is a squashed branch from a previous PR
> fix for gitlab server cert import on linux systems

- defaults/main.yml
- tasks/install-debian.yml
As of gitlab-runner version v17.7.1, when you install a specific version of gitlab-runner that is not the latest version, you must explicitly install the required gitlab-runner-helper-packages for that version. This requirement exists due to an apt/apt-get limitation.
The playbooks fail, as the required dependency is not met and apt can't resolve it automatically.
```
TASK [riemers.ansible-gitlab-runner : (Debian) Install GitLab Runner] **************************************************************************************************************************************
task path: /workspaces/Development/IaC/Ansible/Roles/riemers.ansible-gitlab-runner/tasks/install-debian.yml:45
fatal: [dettlx712.intra.ifm]: FAILED! => {"cache_update_time": 1738662513, "cache_updated": false, "changed": …
```
> fix: install gitlab-runner-helper-packages if version is specified

- defaults/main.yml
- tasks/update-config-runner.yml
In my case my runners are mounting a folder from an internal NAS as their cache folder.
This is working without problems but the role is verifying some permissions and access on this folder that are failing in my case.
I just wanted to add the possiblity to  disable these verifications if not needed by creating a new variable in the default : 
`# controls whether the role verifies permissions and access on the builds_dir and cache_dir (Unix support only)
gitlab_runner_verify_directories: true`
> feat: add possiblity to bypass directory verifications

- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
When setting up an ssh runner, using `gitlab_runner_config_update_mode: by_registering`, we cannot set the `disable_strict_host_key_checking`.
This PR adds the possibility of setting it:
```
gitlab_runner_runners:
- name: "test4"
token: "my token"
url: "https://gitlab.mycompany.com/"
executor: ssh
ssh_user: "mysshuser"
ssh_host: "mysshhost.mycompany.com"
ssh_disable_strict_host_key_checking: true
```
> Add possibility to setup disable_strict_host_key_checking [runners.ssh] in registering mode

- defaults/main.yml
- tasks/main-container.yml
With a config like 
```
gitlab_runner_container_install: true
gitlab_runner_config_update_mode: by_registering
gitlab_unregister_runner_executors_which_are_not_longer_configured: true
gitlab_runner_listen_address: ":9252"
gitlab_runner_container_image: "gitlab/gitlab-runner"
gitlab_runner_container_name: "gitlab-runner"
gitlab_runner_container_tag: "ubuntu-v17.8.3"
gitlab_runner_container_mount_path: "/etc/gitlab-runner"
```
where the metrics are generated on port 9252 and gitlab-runner is deployed as a container, we must be able to map the port to the host.
I propose to add a new variable:
`gitlab_runner_container_published_ports`
where we can list the published ports of the container.
For example
` gitlab_runner_container_published_ports: "9252:9252"`
> Be able to published ports when gitlab-runner is deployed as a container

- tasks/register-runner-container.yml
- tasks/register-runner.yml
When using a config like:
```
gitlab_runner_runners:
- name: "Central-Debug-1"
executor: docker
state: present
docker_image: 'docker:stable'
docker_tlsverify: true
```
in `gitlab_runner_config_update_mode: by_registering`
the registration will fail, as the runner command is constructed with the parameter `--docker-tlsverify: True` instead of `--docker-tlsverify
`
Fixes https://github.com/riemers/ansible-gitlab-runner/issues/365
> Runner not created when docker_tlsverify: true under gitlab_runner_runners

- tasks/install-debian.yml
Fix for https://github.com/riemers/ansible-gitlab-runner/pull/363#issuecomment-2683541935. Tested with gitlab-runner version 17.6.1 and 17.7.0.
> fix: install gitlab runner helpers only for version >= 17.7.0

- tasks/install-debian.yml
Ensure `gitlab_runner_helper_package` is Always Defined
Previously, the task "_(Debian) Install GitLab Runner Helpers_" failed due to `gitlab_runner_helper_package` being undefined.
This issue was introduced by a prior change that unintentionally tried to install gitlab_runner_helper_package_name even when it´s not set.
This PR ensures that `gitlab_runner_helper_package` is always defined, regardless of whether g`itlab_runner_package_version` is set.
closes: #375
> fix: make sure helper package is set

- tasks/update-config-runner.yml
- templates/config.runners.autoscaler/autoscaler.j2
- templates/config.runners.autoscaler/fleeting.plugin.aws.j2
- templates/config.runners.autoscaler/fleeting.plugin.azure.j2
- templates/config.runners.autoscaler/fleeting.plugin.googlecloud.j2
This PR introduces support for GitLab runners utilizing [fleeting-based autoscaling](https://docs.gitlab.com/runner/fleet_scaling/fleeting/). It enables autoscaling configurations for [AWS](https://gitlab.com/gitlab-org/fleeting/plugins/aws), [GCP](https://gitlab.com/gitlab-org/fleeting/plugins/googlecloud), or [Azure ](https://gitlab.com/gitlab-org/fleeting/plugins/azure)fleeting plugins.
**New Feature**
The following YAML input is now supported for configuring autoscaling:
```yml
gitlab_runner_runners:
- name: "runner-name" 
token: "runner-token" 
executor: "docker-autoscaler"
docker_image: "alpine"
autoscaler:
plugin: "azure"
capacity_per_instance: 1
max_use_count: 1
max_instances: 10
plugin_config:
name: "scaleset-name" 
subscription_id: "subs-id" 
resource_group_name: "rg-name" …
```
> feat: add fleeting autoscale support closes #372

- tasks/main-container.yml
In our environment we exclusively use docker to run our runners (heh).
Right now, the published_ports variable is mandatory. We do not want to publish any ports, so we didn't define it. 
This leads to the following: 
This PR fixes that :)
> Made published_ports for docker optional

- defaults/main.yml
This PR makes the published_ports default var a list, instead of a string. `default(omit)` didn't fully fix our issue in #379, this did.
> Make published_ports default var a list, as needed in docker module

- tasks/install-redhat.yml
GitLab is not hosting a repo for CentOS Stream 10 yet, so as a workaround, the Stream 9 Repo must be used. I've tested it on a fresh server and it works flawlessly.
> CentOS Stream 10 workaround

- tasks/register-runner.yml
- tasks/unregister-runner.yml
If using `gitlab_runner_config_update_mode: 'by_registering'` and `gitlab_runner_system_mode: true` (the default), you'll need root permissions to unregister/register again.
This is a similar problem to the one fixed in https://github.com/riemers/ansible-gitlab-runner/pull/395.
> Allow unregistering without global become: true
