- defaults/main.yml
- handlers/main.yml
- tasks/global-setup.yml
Hello,
Would you mind including this modifications to your role?
- Added docker executor 'privileged' configurable option.
- Added handler to restart gitlab-runner service on global setup change.
Romain
> Docker privileged

- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- tasks/register-runner.yml
- Remove ssh variable requirement
- set docker-volumes correctly for 10.x
- add locked variable
closes #8, #7
> Clean up scripts

- README.md
- tasks/register-runner.yml
> s3 support added

- tasks/register-runner.yml
Looks like there is a typo in last PR.
> Fixed S3 secret key configuration

- tasks/register-runner.yml
> Prepend each docker volume entry with `--docker-volumes`

- tasks/register-runner.yml
> Fix multi-line string for runner registration command

- tasks/register-runner.yml
> Enable Docker privileged mode at runner registration if desired

- tasks/install-redhat.yml
> Update to leverage gitlab's install script

- tasks/config-runner.yml
- tasks/main.yml
- tasks/register-runner.yml
Also append a serial number for uniquenes.
> Use default to cope for missing runner name

- handlers/main.yml
- tasks/update-config-runner.yml
The reload handler throws an error message (see #39) so use restart instead.
> Use restart  instead of reload handler

- tasks/register-runner.yml
Signed-off-by: Jean Wasilewski <jwasilewski@online.net>
> allow runner specific token

- tasks/register-runner.yml
Signed-off-by: Jean Wasilewski <jwasilewski@online.net>
> Bucket location should not be mandatory

- README.md
Since the changes in #58.
Closes #61
> readme: update Ansible requirements to v2.7+

- defaults/main.yml
- tasks/register-runner.yml
- tasks/update-config-runner.yml
Signed-off-by: Nicolas Gelot <nicofonk@gmail.com>
> Add support of output_limit parameter

- defaults/main.yml
- tasks/config-runners.yml
- tasks/global-setup.yml
- tasks/install-debian.yml
- tasks/install-redhat.yml
- tasks/register-runner.yml
Fixes https://github.com/riemers/ansible-gitlab-runner/issues/70.
> Allow running role without global become: true

- .travis.yml
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- tasks/Unix.yml
- tasks/Windows.yml
- tasks/config-runner-windows.yml
- tasks/config-runners-windows.yml
- tasks/global-setup-windows.yml
- tasks/install-windows.yml
- tasks/line-config-runner-windows.yml
- tasks/main.yml
- tasks/register-runner-windows.yml
- tasks/update-config-runner-windows.yml
- tests/test.yml
- tests/travis-bootstrap-ansible.ps1
- tests/vars/Windows.yml
- tests/vars/default.yml
- vars/Darwin.yml
- vars/Windows.yml
Hey Erik-Jan,
I needed to extend your role to also support windows since we have to maintain windows runners as well. I followed your pretty impressive work as much as I could - but I had to copy quite some bits and pieces to have the windows specific ansible modules addressed correctly. There currently also seems to be a **bug** in ansible with the **assemble** command that is not working on windows properly, therefore I had to mimic the functionality using powershell commands.
I did test the role on our machines but was not able to integrate it into your **travis ci**.
Let me know what you think, I'd be happy to make adaptions if needed.
> Windows support

- tasks/update-config-runner.yml
Looks like I missed some escapes in the regexps
> Fixed excaping in regexps

- defaults/main.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
1. Fix for a typo in the regexp for url when inserting the environment
2. Addition of 'pre_clone_script' which is needed for installation behind a proxy
> Small fix and addition of config parameter 'pre_clone_script'

- tasks/register-runner.yml
- tasks/update-config-runner.yml
Please take a look @riemers  :)
This is only for *nix, I don't have any experience with Windows runner.
> Fix #104 add tls_verify and dns option

- defaults/main.yml
- tasks/register-runner.yml
references vars for aws autoscaling settings in readme.
Issue #85
> feat: add docker machine options for aws autoscaling.

- tasks/register-runner-windows.yml
- tasks/register-runner.yml
Relates to https://github.com/riemers/ansible-gitlab-runner/issues/44
> added default image for docker installs

- tasks/update-config-runner.yml
> Missed brackets

- tasks/install-debian.yml
Fixing problems on debian buster described here:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4092
https://docs.gitlab.com/runner/install/linux-repository.html#disable-skel
> :bug: Special handling on debian buster

- defaults/main.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/update-config-runner-windows.yml
- tasks/update-config-runner.yml
Hey,
Thanks for the role! I needed to be able to configure pre_build script, so here's a small PR to add just that.
Cheers,
--Kieran
> Add pre / post build script configuration

- defaults/main.yml
- handlers/main.yml
- tasks/Container.yml
- tasks/config-runner-container.yml
- tasks/config-runners-container.yml
- tasks/install-container.yml
- tasks/main.yml
- tasks/register-runner-container.yml
- tasks/update-config-runner.yml
- tests/test.yml
- vars/default.yml
Initial cut at installing and registering gitlab-runner in a container... Open to comments
> Enable running the runner in a docker container

- defaults/main.yml
- tasks/line-config-runner-windows.yml
- tasks/line-config-runner.yml
Fix type of keys in extra config
https://docs.gitlab.com/runner/configuration/advanced-configuration.html
https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/541
> Error on 'Assemble new config.toml' FATAL: Failed to verify runners

- tasks/Container.yml
- vars/default.yml
Adding the docker restart flag to the docker container. Default: "unless-stopped"
> Adds restart policy to docker container

- tasks/Unix.yml
- tasks/register-runner-container.yml
- tasks/register-runner.yml
- tasks/update-config-runner.yml
- added missing disable_cache docker runner config option 
- added missing pull_policy docker runner config option
- removed empty lines
- fixed insertafter config at docker volumes and docker devices options
> Add disable_cache and pull_policy docker options and minor fixes

- .gitignore
- tasks/Unix.yml
Remove previously added feature, because it is not in scope of this role.
> Remove adding gitlab-runner user to docker group

- README.md
- defaults/main.yml
- tasks/update-config-runner.yml
> Add support for Azure cache.

- defaults/main.yml
- tasks/register-runner.yml
- tasks/update-config-runner.yml
Allow to configure TLS CA File
> add tls_ca_file parameter

- vars/Darwin.yml
> Set proper homebrew path for OS X ARM variant

- tasks/Container.yml
- tasks/install-container.yml
- tasks/register-runner-container.yml
> Fix hardcoded defaults

- defaults/main.yml
- tasks/register-runner.yml
- tasks/update-config-runner.yml
Allows for setting and updating the helper_image option for docker executors.
> Enable setting the helper_image option for docker executors

- tasks/update-config-runner.yml
This is a simple fix to issue #228
> Bugfix issue #228

- defaults/main.yml
- handlers/main.yml
- tasks/install-macos.yml
> feat: add option not to start gitlab runner on macos

- defaults/main.yml
> fix for undefined variables error

- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
- tasks/update-config-runner-windows.yml
It adds the docker network_mode to the register command.
> Add network_mode option to registration command

- tasks/list-configured-runners-container.yml
Fixes https://github.com/riemers/ansible-gitlab-runner/issues/284
> Fix json deserialization problem due to trailing empty line

- tasks/register-runner-container.yml
- tasks/register-runner-windows.yml
- tasks/register-runner.yml
> recognize cache options for gcp and azure during register

- README.md
Added a small section linking to the issue that documents how to run as a different user
> Run as a user other than gitlab-runner

- .github/workflows/stale.yml
Fix a auto-linter-correction mistake in the github state.yml
> Fix state.yml

- tasks/list-configured-runners-unix.yml
This reverts commit 31bed722650386cfa38c646c2656b5ef303eaad4.
> Revert "Update list-configured-runners-unix.yml"
